steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: "backend"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/toads-backend:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  dir: "backend"
  args: ["push", "gcr.io/$PROJECT_ID/toads-backend:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/backend', 'backend=gcr.io/$PROJECT_ID/toads-backend:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=toad-cluster'