apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "frontend-ip"
spec:
  backend:
    serviceName: frontend
    servicePort: 80