apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: imageproxy
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "imageproxy"
spec:
  backend:
    serviceName: imageproxy
    servicePort: 8080