apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      volumes:
      - name: gstorage-key
        secret:
          secretName: gstorage-key
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: ORIGIN
          value: toads.app
        - name: HOSTNAME
          value: https://toads.app
        - name: DB_CONNECTION_STRING
          value: "postgres://postgres@pgbouncer/toads"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-email
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-email
        image: gcr.io/toads-208000/toads-backend:9eb41a82808f17c4e45061525a3b840a570b1c0b
        imagePullPolicy: Always
        name: backend
        volumeMounts:
        - name: gstorage-key
          mountPath: /var/secrets/google
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1