apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      volumes:
      - name: gstorage-key
        secret:
          secretName: gstorage-key
      containers:
      - env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: production
        - name: ORIGIN
          value: toads.app
        - name: HOSTNAME
          value: https://toads.app
        - name: REDIS_HOST
          value: redis-prod
        - name: REDIS_PORT
          value: "6379"      
        - name: DB_CONNECTION_STRING
          value: "postgres://postgres@pgbouncer/toads"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-email
        - name: CDN_KEY
          valueFrom:
            secretKeyRef:
              key: cdn_key
              name: cloudsigning
        - name: CDN_KEY_NAME
          valueFrom:
            secretKeyRef:
              key: key_name
              name: cloudsigning
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-email
        image: gcr.io/toads-208000/toads-backend:ab24be17234ac1a7fb2cb198dfa45512bb989e4e
        imagePullPolicy: Always
        name: backend
        volumeMounts:
        - name: gstorage-key
          mountPath: /var/secrets/google
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1