apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: imageproxy
  name: imageproxy
  selfLink: /api/v1/namespaces/default/services/imageproxy
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: imageproxy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}